### ISSUE TITLE
Django 1.6 -- simplejson Deprecated

### ISSUE THREAD

**Issue by lylepratt** [zapier/django-rest-hooks#10]
`simplejson` is deprecated in Django 1.6. This repo imports `simplejson` which results in warnings:
https://github.com/zapier/django-rest-hooks/search?utf8=%E2%9C%93&q=simplejson

Please update!

**Comment by lylepratt** [comment]
Looks like there is already a PR for this:
https://github.com/zapier/django-rest-hooks/pull/5

**Comment by bryanhelmig** [comment]
Sorted in linked PR!
