### ISSUE TITLE
Question :: why do we need the user property on each model?

### ISSUE THREAD

**Issue by laginha** [zapier/django-rest-hooks#15]
I was looking for django apps for web hooks when I found this project. I find it useful but I was wondering why you need a user field/property/attribute on the model to hook it. I understand you use it to filter and trigger hooks. I just don't get the reasoning.

If you have two hooks

```python
Hook(
    user=jrrtolkien,
    event='book.created',
    target='http://example.com/target1'
).save()
Hook(
    user=grrmartin,
    event='book.created',
    target='http://example.com/target2'
).save()
```

when a new book is created

```python
Book(
    user=jrrtolkien,
    title='The Two Towers',
    pages=327,
    fiction=True
).save()
```

only the user *jrrtolkien* will get a notification. Which means a user cannot "subscribe" events related to other users (*grrmartin* won't know *jrrtolkien* wrote a new book). 
Am I wrong?

**Comment by bryanhelmig** [comment]
Nope - that is desired behavior. The main audience for this are private apps - not public apps. IE: you wouldn't want two sales teams from two difference companies to get each others' leads.

If you want to create a public channel of hooks/notifications - you'll probably have to fork.

**Comment by meric** [comment]
You can subscribe to signals manually and publish the events to multiple users.

    for user in users:
        hook_event.send(
            sender=sender,
            user=user,
            action=action,
            instance=instance)

**Comment by avelis** [comment]
@laginha If you want to look into a fork that has done some work in this area, check out press labs.

https://github.com/PressLabs/django-rest-hooks-ng

Disclaimer their initial migration file already diverges from the original Hook model schema.

**Comment by laginha** [comment]
Thanks guys!

But I've realised I also need WebHooks on a model-instance level (e.g. receive updates on a vehicle's location). In that case, it seems `django-rest-hooks` isn't fit for me, since I need to specify the events on `HOOK_EVENTS` for model-class level actions (`App.Model.Action`). 

I guess the best approach for me is to add a generic relation to the model `Hook` and handle `post_save` signals myself..

**Comment by meric** [comment]
Hi laginha - your problem is you couldn't link user to the vehicle. I've done it in my application by doing it in reverse using a OneToOneField.

How about this:

```
class Vehicle(models.Model):
    hook = models.OneToOneField(Hook, related_name="vehicle")
    # other fields

@receiver(post_save, sender=SomeModel)
def on_post_save(sender, instance, **kwargs):
     hooks = Hook.objects.filter(vehicle__somefield_someotherfield=instance)
     for hook in hooks: 
          hook_event.send(
              sender=sender,
              user=hook.vehicle.user,
              action="someaction",
              instance=instance)
```

**Comment by laginha** [comment]
Yeah that works.
Although I would have to had that `OnetoOneField` relation in every 'hookable' model and a signal receiver for each sender. But it might be the best solution nonetheless.

Thanks!

**Comment by meric** [comment]
@laginha You don't need it in every 'hookable' model. I think my previous example wasn't quite right. I think I was mistaken about the `OneToOneField`, I didn't use it for this purpose. You just need one receiver per model.

Here is the corrected example:

```
class Vehicle(models.Model):
    user = models.ForeignKey(Hook, related_name="vehicle")
    # other fields

@receiver(post_save, sender=SomeModel)
def on_post_save(sender, instance, **kwargs):
     users = User.objects.filter(vehicle__somefield_someotherfield=instance)
     for user in users: 
          hook_event.send(
              sender=sender,
              user=user,
              action="saved",
              instance=instance)
```

**Comment by laginha** [comment]
@meric I've realised would be limiting a vehicle to one hook only in your previous comment. And I'm not sure if I understood your latest comment.

What I need is for the `Hook` model to behave like a weak entity between `User` and any 'hookable' model. Hence a user may 'follow' a specific `Vehicle` instance (and not all vehicles).

I'm going for the generic relation solution. In this way I can have a single generic receiver handling a `post_save` signal:

```python 
@receiver(post_save)
def on_post_save(sender, instance, **kwargs):
    if sender in HOOKABLE_MODELS:
        ct = ContentType.objects.get_for_model(sender)
        hooks = Hook.objects.filter(content_type__pk=ct.pk, object_id=instance.pk)
        for hook in hooks:
            hook.deliver_hook(instance)
```
