### ISSUE TITLE
Support Django 1.9 depreciations

### ISSUE THREAD

**Issue by imsickofmaps** [zapier/django-rest-hooks#22]
https://github.com/zapier/django-rest-hooks/blob/master/rest_hooks/utils.py#L8 needs updating to:

```python
try:
    from importlib import import_module
except:
    from django.utils.importlib import import_module
```

**Comment by imsickofmaps** [comment]
I tried to make this change but because you rely on the standalone comment framework stuff for your tests, which relies on sites framework, which now requires domain to be [UNIQUE](https://docs.djangoproject.com/en/1.9/ref/contrib/sites/#module-django.contrib.sites), the tests fail before I even get to fix this.

**Comment by avelis** [comment]
@imsickofmaps I appreciate you bringing me this to my attention. I will look into this shortly.

**Comment by avelis** [comment]
@imsickofmaps I made a branch for Django 1.9 support and fixes. I was able to make a commit to fix your issue but ran into a test failure along the way. Branching for now to not lose the work I have thus far.

**Comment by imsickofmaps** [comment]
@avelis you forgot to include this in Django 1.9 fixes. It still breaks when you use the celery task method by setting `HOOK_DELIVERER`

**Comment by imsickofmaps** [comment]
@avelis sorry - wrong root issue, you did fix it, you didn't release it to pypi! Still on 1.2.0 ... from December

**Comment by avelis** [comment]
@imsickofmaps you are absolutely correct. I am a project contributor but not the PyPi owner. I will reach out to zapier to make a PyPi release soon.

In the mean time, I did make a Github release which you can reference the tarball directly.

**Comment by imsickofmaps** [comment]
@avelis thanks! That's fine for dev but we use setuptools for production builds and it's super painful. Do they release pretty sharpish?

**Comment by avelis** [comment]
@imsickofmaps They usually are. I have a previous correspondence with them going back to the 20th of January. I have re-ignited that thread to see if there is an update.

Usually when I make a request I get a reply and release EOD.

I will update you and this ticket when I hear from them or see a PyPi release.

**Comment by avelis** [comment]
@imsickofmaps Zapier made a PyPi release.

Please see: https://pypi.python.org/pypi/django-rest-hooks/1.2.1

**Comment by bryanhelmig** [comment]
Sorry about the delay folks - total failure of the brain! @avelis definitely asked for a release and I definitely spazzed. :-)

**Comment by imsickofmaps** [comment]
@bryanhelmig awesome! Thanks to you and @avelis ... BTW - if you want to extract yourself from the blockage in future - you could use: https://docs.travis-ci.com/user/deployment/pypi ... I work with a couple of projects that do that.

**Comment by avelis** [comment]
@imsickofmaps Thanks for point that out. I will definitely look into that!
