### ISSUE TITLE
Passing instance forces pickle

### ISSUE THREAD

**Issue by imsickofmaps** [zapier/django-rest-hooks#24]
Because of the last two params on this line here: https://github.com/zapier/django-rest-hooks/blob/master/rest_hooks/models.py#L88 if you want to use a celery task to move the processing to an async task with celery you are forced to use pickle for task serialization which is bad: http://docs.celeryproject.org/en/latest/faq.html#isn-t-using-pickle-a-security-concern

Given the `payload` is the json serialized object, do we need to pass through the `instance`? Also, if the `hook` must be passed in, could it be `hook.id`?

**Comment by bryanhelmig** [comment]
We do this @imsickofmaps:

```python
HOOK_DELIVERER = 'some.path.custom_delivery_function'

def custom_delivery_function(target, payload, instance, hook):
    kwargs = dict(target=target, payload=payload,
                  instance_id=instance.id, hook_id=hook.id)
    SomeTask.apply_async(kwargs=kwargs)
```

**Comment by imsickofmaps** [comment]
@bryanhelmig ah of course! Perhaps I'll make a PR for the docs then that provides the updated advice.

**Comment by bryanhelmig** [comment]
That would be super kind of you, thank you!
