### ISSUE TITLE
Django asks for new migration every time the HOOK_EVENTS settings is changed.

### ISSUE THREAD

**Issue by emanuelcds** [zapier/django-rest-hooks#27]
It's really annoying because every time we change our hooks it asks for a new migration. It would not be a problem if we can generate this migration inside our application, but it's being generated inside the rest_hooks package library itself. Anyone with the same problem? Using **Django v1.8.3** here.

**Comment by avelis** [comment]
@emanuelcds According to the following answer: http://stackoverflow.com/a/26186194/153262

This is Django's preffered choice:
> This is by design. There are several reasons, not least of which for me that datamigrations at points in history need to have a full accurate representation of the models, including all their options not just those which affect the database

`django-rest-hooks` persists a choices dynamic to a given developers project. Therefore, this request can go a little against Django's design guideline.

One alternative I have read is to turn the `choice` value in the **Hook.event** CharField to reference a method that returns a tuple or list of tuples. This can allow for flexibility in choices in a developers project settings and still allow the choices to persist via framework validation.

**Comment by avelis** [comment]
@emanuelcds re: #28 

I appreciate the effort in making a PR to resolve this. Taking a quick look at the change, I am worried that removing the reference to the choice argument will have side effects that could break some default functionality.

One I can think of is the ability to select an event choice as a dropdown via a model admin view or a navigational view within a developers project.

I believe using a method as the choice argument can still allow for dropdown behavior while reducing data migrations whenever a developer decides to change the dictionary of **HOOK_EVENTS** within their project.

**Comment by emanuelcds** [comment]
The problem is the data migration is generated inside the django-rest-hooks library.
If you are using virtualenv or any other environment controller, you will loose the database control very easy because the new migrations will not be versioned with your application code. A dropdown with current HOOK_EVENTS values can be inserted in the admin easily. Although, the real issue IMHO is the library architecture is not using a simple foreign key for this purpose. Instead adding it in the HOOK_EVENTS, you can just create it directly in the admin if there is a model holding de entries that are being used in this dictionary. Tell me if you agree with this approach, so I can implement here and create a new pull request.

By the way, I'm having another issue here. Event fixing this one, in Django 1.8.3 its asking to generate a new migration because the first one (0001_initial) was generated using bytearray strings (b'string') in the field names. As the models are not declared same way, its asking for an alter migrations. I will try to fix this one and keep you posted about the progress.

**Comment by emanuelcds** [comment]
I pushed the fixes. I would appreciate if you can take a look there.

**Comment by avelis** [comment]
@emanuelcds I apologize for not getting to this sooner. I took a quick glance and I appreciate you addressing the concerns I talked about. I will likely merge this PR in.

If you can, I would also appreciate some documentation on the HookForm, HookAdmin class and it's usage.

**Comment by avelis** [comment]
@emanuelcds As a general question I am unsure if this would be "backwards" compatible with current expectations. If that is the case then I might move to making a release reflecting that change (e.g. `v2.0.0`).

**Comment by emanuelcds** [comment]
Actually nothing major changed. It does not affects previous versions once it does not generates new migrations nor data migrations. You can test it yourself (like we did here). I manually tested it. Just keep in mind that this is a serious issue that affects database migrations and probably there is not a lot of open issues because there is only a few projects using it. Do you think I can do anything to help you to merge it? If no, please close this PR and we look forward for any further version bump.

**Comment by avelis** [comment]
@emanuelcds I merged it in. If you can at least write some basic docs on the new classes on the README I would appreciate it.

I will move to make a release soon.

**Comment by emanuelcds** [comment]
Thank you very much. I will document the changes made on the README and open a new PR.

**Comment by emanuelcds** [comment]
Done.
I believe you can close this Issue.
Thank you.
