### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Korijn** [zapier/django-rest-hooks#30]
We're working on a conda recipe for this package at https://github.com/conda-forge/staged-recipes/pull/823 and [we're wondering](https://github.com/conda-forge/staged-recipes/pull/823#discussion_r67681995) what version of the BSD license specifically (2-Clause or 3-Clause) you're using?

**Comment by avelis** [comment]
@bryanhelmig would you know of any resources we could tap into for clarity on the which BSD license django-rest-hooks works best under?

For reference:
[2-Clause BSD Language](http://choosealicense.com/licenses/bsd-2-clause/)
[3-Clause BSD Language](http://choosealicense.com/licenses/bsd-3-clause/)

Notes:
* Paraphrased: "A 3rd clause prohibits others from using the name of the project or its contributors to promote derived products without written consent."

**Comment by bryanhelmig** [comment]
3 clause is 💯 .

**Comment by Korijn** [comment]
Thanks for the quick reply! To be sure: everyone agrees that the license field of the recipe can be updated to say `BSD 3-Clause`?

**Comment by bryanhelmig** [comment]
Sure - I don't mind multi-licensing this - MIT, ISC and BSD 3-clause. Pick which one you want. 👍
