### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Nolapete** [zapier/django-rest-hooks#36]
I think django-rest-hooks would be a good fit for a project I'm working on but would like to be sure before I head down the path of using it.

I have a django rest framework serializer already working from a view input.

I'd like to have this done as a scheduled event rather than manually.

1) read JSON data in using requests to get a list of imdb ids and showtimes from our POS system
2) serializer would then add the films into django. 

Is this a good fit?

**Comment by avelis** [comment]
@Nolapete It depends. Could you elaborate more on what problem django-rest-hooks is alleviating for you? This will help me better understand if this library is the right fit for your issue.

It almost sounds like Celery could achieve what you are looking for using async task processing.

**Comment by Nolapete** [comment]
I've been exploring Celery as an option, but django-rest-hooks looked like it could work.  I'll try to integrate the example into my project and see if it does.
