### ISSUE TITLE
Zapier sends 'target_url' in the request and 'target' is expected.

### ISSUE THREAD

**Issue by teewuane** [zapier/django-rest-hooks#40]
When Zapier POSTs to my `/api/v1/hooks/` uri, it sends this as the data...

`{"subscription_url": "https://zapier.com/hooks/standard/1453504/8a7907ee05a54e68be99bcdc969155c6/", "target_url": "https://zapier.com/hooks/standard/1453504/8a7907ee05a54e68be99bcdc969155c6/", "event": "entry.created"}`

To create a Hook Resource you need to provide `user`, `event`, and `target`.

The target is specified but it is `target_url` not `target`. (It also appears to be in `subscription_url`)  

So the new resource is created but the `target` field is empty.

I realize I can just overwrite my Hook Resource's obj_create method and map `target_url` to `target` but it seems that these key names should match up. :)

Is my understanding correct?

**Comment by bryanhelmig** [comment]
Hey @teewuane -  this repository isn't platform support for Zapier. We have a short section that mentions https://zapier.com/developer/documentation/v2/platform/#who-can-help-me. We have engineers at contact@zapier.com who can answer this!

**Comment by teewuane** [comment]
Thanks for the response, @bryanhelmig. To be clear, I wasn't looking for help or support on the Zapier platform.  The reason I opened the issue was to question why the field is named 'target' and not 'target_url'. I would guess that most people using this app in their projects are using it to interact with Zapier (even though it's a rest hooks app could be used anywhere and it's not called "django-zapier-rest-hooks" of reason :)) so it makes sense to me to have the field match. Either way, I have it working in my project just fine :) thanks again!

**Comment by psaniko** [comment]
In case someone stumbles upon the same problem. Instead of modifying the hook model I opted to change the field names via Zapier's scripting feature:

```javascript
'use strict';

var Zap = {

    pre_subscribe: function(bundle) {
        var data = z.JSON.parse(bundle.request.data);
        data.target = data.target_url;
        delete data.target_url;
        bundle.request.data = JSON.stringify(data);

        return bundle.request;
    },

    pre_unsubscribe: function(bundle) {
        var data = z.JSON.parse(bundle.request.data);
        data.target = data.target_url;
        delete data.target_url;
        bundle.request.data = JSON.stringify(data);

        return bundle.request;
    }

};
```
