### ISSUE TITLE
Support for Django 1.10 and future versions?

### ISSUE THREAD

**Issue by pombredanne** [zapier/django-rest-hooks#41]
I see the dev requirements are no covering Django 1.10?
Any plan to support this? and beyond?

**Comment by avelis** [comment]
@pombredanne Yes, of course. Just haven't gotten around to adding it. If you have time and want to open a PR in the meantime I am all for it.

**Comment by pombredanne** [comment]
@avelis Thanks for the quick reply. At the moment I am considering this vs. thorn. So the question is more to make sure that it is worth for me to evaluate this at all. I run only 1.10 and keep close to the latest versions

**Comment by avelis** [comment]
@pombredanne Oh wow, I didn't know about thorn. Very cool!

Django 1.10 will be supported just haven't gotten around to making additions for it yet.

**Comment by tdruez** [comment]
@avelis I've been running django-rest-hooks under Python 3.6 and Django 1.11, no issues so far.
I think it's safe to add Python 3.5/3.6 and Django 1.10/1.11 to the tests matrix ;)

**Comment by avelis** [comment]
@tdruez Fair enough. I will look into adding it soon.

**Comment by avelis** [comment]
Addressed in commit: https://github.com/zapier/django-rest-hooks/commit/7062327bb7b0bbc8bb2b1e5bf4886a83844f7c4c
