### ISSUE TITLE
Add ability to extend and customize the Hook model

### ISSUE THREAD

**Issue by tdruez** [zapier/django-rest-hooks#43]
Provide an `AbstractHook` abstract model class that could be easily implemented in the local Django project to support all kind of customizations.

This would also require a settings to override the default usage of the `Hook` model to retrieve the proper Hook objects from the custom model.

**Comment by avelis** [comment]
@tdruez I think this is a great feature to add. Always welcome a PR.

**Comment by tdruez** [comment]
@avelis Thanks++ for pushing the new 1.4.0 release! Would you mind to also publish the package as a wheel on pypi?

**Comment by avelis** [comment]
@tdruez I can look into that soon. That will likely require another release though.

**Comment by tdruez** [comment]
@avelis Thanks, see https://github.com/vandersonmota/model_mommy/pull/298/files#diff-380c6a8ebbbce17d55d50ef17d3cf906 for a PR example.
All that should be needed is to add:
```
[wheel]
universal = 1
```
in a `setup.cfg` file and add `bdist_wheel` in the `setup.py` upload command.

**Comment by tdruez** [comment]
@avelis did you had the chance to look into releasing as a wheel?

**Comment by avelis** [comment]
@tdruez I made a release but it did not upload the wheel. Digging further into the TravisCI config docs and it looks like we are missing some quotes.

https://docs.travis-ci.com/user/deployment/pypi/#Uploading-different-distributions

**Comment by avelis** [comment]
@tdruez I made the required changes to the TravisCI configuration. It still didn't create a wheel for v1.4.2. I might have to contact TravisCI support to see what I am doing incorrectly.

**Comment by tdruez** [comment]
@avelis thanks for giving this a shot ;)
Could you publish it manually while figuring out the Travis issue?

**Comment by tdruez** [comment]
@avelis Thanks for the wheel!
I'm closing the issue :)
